<a href="https://colab.research.google.com/github/pranabsarma18/Python-Codes/blob/main/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here
vec = np.zeros(10)
vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
#Code here
a = int(input("First number: "))
b = int(input("Second number: "))
random_array = np.random.rand(a,b)
print(random_array)
print(random_array.mean())

First number: 2
Second number: 2
[[0.67497167 0.17193086]
 [0.68070407 0.41639526]]
0.48600046324474055


In [4]:
import numpy as np

a = int(input("Enter the number of rows for the array: "))
b = int(input("Enter the number of columns for the array: "))

# Generate the array
arr = np.random.rand(a, b)

# Print the array
print("The generated array:")
print(arr)

# Print the average of the array
print("The average of the array is: ",arr.mean())


Enter the number of rows for the array: 2
Enter the number of columns for the array: 2
The generated array:
[[0.4742878  0.05976196]
 [0.66955326 0.73185253]]
The average of the array is:  0.4838638896711951


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [5]:
#Code here
import numpy as np

def border_array(shape):
    a, b = shape
    arr = np.zeros(shape)
    arr[0,:] = 1
    arr[-1,:] = 1
    arr[:,0] = 1
    arr[:,-1] = 1
    return arr

shape = (4,5)
result = border_array(shape)
print(result)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [6]:
#Code here
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [7]:
vector = np.random.rand(10)
print(vector)

[0.03941891 0.33780762 0.90489817 0.19191086 0.92379062 0.11512041
 0.41440086 0.58110183 0.33520981 0.99562755]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [8]:
#Code here
import numpy as np

matrix = np.eye(3,4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [9]:
#Code here
matrix = np.zeros((5,5))*4
matrix = matrix + np.array([0,1,2,3,4])

print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [10]:
#code here
import numpy as np
# Create random integer vector of shape (10,2) representing coordinates
coords = np.random.randint(1, 100, size=(10, 2))
print(coords)
# Coordinates of the given point
point = np.array([50, 50])
# Calculate the distance between the point and each point in the vector
distances = np.linalg.norm(coords - point, axis=1)
# Round to the nearest integer
distances = np.round(distances)
# convert to int
distances = distances.astype(int)
print(distances)

[[68 16]
 [ 6  7]
 [37 96]
 [28 52]
 [13 88]
 [37 65]
 [76 46]
 [45  1]
 [12 61]
 [16 77]]
[38 62 48 22 53 20 26 49 40 43]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
#Code here
import numpy as np

# shape of the array
shape = (6, 7, 8)

# index of the 100th element
index = 99

# get the indices in each dimension
x, y, z = np.unravel_index(index, shape)

print("Indices of the 100th element: (x,y,z) = ({},{},{})".format(x, y, z))

Indices of the 100th element: (x,y,z) = (1,5,3)


In [12]:
np.unravel_index?

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [13]:
#Code here
import numpy as np

# Input: space separated numbers as a string
numbers = input()

# Convert the string of numbers to a list of integers
numbers_list = list(map(float, numbers.split()))

# Create a NumPy array from the list
numbers_array = np.array(numbers_list)

# Reverse the array
reversed_array = np.flip(numbers_array)

# Print the reversed array with type float
print(reversed_array.astype(float))

1 -3 -7 2 67
[67.  2. -7. -3.  1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [15]:
#Code here
len(np.array([1, 2]))

2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [19]:
#Code here
def soft_max(y):
    y = np.array(y)
    if y.shape == (len(y), ):
        return np.exp(y)/np.exp(y).sum()

In [20]:
soft_max([33.17344305, 45.61961654, 82.05405781, 80.9647098, 68.82830233, 91.52064278])

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

In [21]:
import numpy as np

def softmax(arr):
    if not isinstance(arr, np.ndarray) or arr.ndim != 1:
        raise ValueError("Input should be a 1D numpy array.")

    # Calculation of the Softmax
    exp_arr = np.exp(arr)
    return exp_arr / np.sum(exp_arr)

In [26]:
arr = np.array([1, 2, 3])
print(softmax(arr))

[0.09003057 0.24472847 0.66524096]


In [25]:
try:
    softmax(np.array([[1, 0],[0, 1]]))
except ValueError:
    print("Input should be a 1D numpy array")

Input should be a 1D numpy array


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [27]:
#Coder here
import numpy as np

def stack_vertically(*args):
    for arr in args:
        if not isinstance(arr, np.ndarray):
            raise ValueError("All input should be numpy array.")
    return np.vstack(args)

In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
result = stack_vertically(arr1, arr2, arr3)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [32]:
import numpy as np
from datetime import datetime, timedelta

def date_array(start_date, end_date):
    if not (isinstance(start_date, str) and isinstance(end_date, str)):
        raise ValueError("Both start_date and end_date should be string")
    try:
        start_date = datetime.strptime(start_date, '%Y-%m-%d')
        end_date = datetime.strptime(end_date, '%Y-%m-%d')
    except ValueError:
        raise ValueError("Date format should be YYYY-MM-DD")
    if start_date > end_date:
        raise ValueError("End date should be greater than start date")
    date_list = [start_date + timedelta(days=x) for x in range(0, (end_date-start_date).days+1)]
    date_array = np.array([date.strftime('%Y-%m-%d') for date in date_list])
    return date_array

In [33]:
start_date = "2020-09-15"
end_date = "2020-09-25"
result = date_array(start_date, end_date)
print(result)

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


###`Q-14:` Subtract the mean of each row from a matrix.

In [40]:
#code here
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print()
# calculate the mean of each row
row_means = matrix.mean(axis=1)
print(row_means)
print()
print(row_means.reshape(-1,1))
print()
# subtract the mean of each row from the matrix
#result = matrix - row_means[:, np.newaxis]
result = matrix - row_means.reshape(-1,1)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[2. 5. 8.]

[[2.]
 [5.]
 [8.]]

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [45]:
#Code here
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print()
# Get the column 1 and column 2
col1 = matrix[:, 0].copy()
col2 = matrix[:, 1].copy()

# Swap the columns
matrix[:, 0] = col2
matrix[:, 1] = col1

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 1 3]
 [5 4 6]
 [8 7 9]]


###`Q-16:` Replace odd elements in arrays with -1.

In [52]:
#Code here
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Get the indices of odd elements
indices = np.where(arr % 2 == 1)
print(indices)

# Replace odd elements with -1
arr[indices] = -1

print(arr)

(array([0, 2, 4, 6, 8]),)
[-1  2 -1  4 -1  6 -1  8 -1]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [54]:
#Code here
import numpy as np

arr1 = np.array([6,3,1,5,8])
arr2 = np.array([3,2,1,7,2])

# Get the max values of the two arrays
result = np.maximum(arr1, arr2)

print(result)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [56]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[4054, 4258, 2146,  847, 9052],
       [5573, 4200, 3111, 7216,  752],
       [8854, 4455,  705, 3330, 4166],
       [4593, 3862, 7208,  180, 3012],
       [ 536, 4720, 2360, 5949, 3975],
       [1839, 1402,  684, 9085, 5293],
       [5607, 6028, 7362, 8395, 6918],
       [5040, 5071, 8206, 4288, 5747]])

In [55]:
#Code here
def norm_array(X):
    return (X - X.mean())/(X.max() - X.min())

In [57]:
norm_array(arr1)

array([[-0.05030601, -0.02739753, -0.26456766, -0.41044076,  0.51095171],
       [ 0.12027232, -0.03391072, -0.15620157,  0.30477541, -0.42110893],
       [ 0.48871701, -0.00527513, -0.42638686, -0.13160865, -0.0377288 ],
       [ 0.01022179, -0.07186693,  0.30387704, -0.4853425 , -0.16731892],
       [-0.44536496,  0.02448344, -0.24053622,  0.16249579, -0.05917743],
       [-0.29904267, -0.34811623, -0.42874509,  0.5146575 ,  0.08882931],
       [ 0.1240904 ,  0.17136721,  0.32117069,  0.43717294,  0.27131106],
       [ 0.0604183 ,  0.06389949,  0.41594891, -0.02402864,  0.1398119 ]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [63]:
#Code here
import numpy as np

def nth_largest(arr, n):
    if not isinstance(arr, np.ndarray) or arr.ndim != 1:
        raise ValueError("Input must be a 1D numpy array.")
    if not isinstance(n, int) or n > len(arr):
        raise ValueError("n must be an integer less than or equal to the length of the array.")
    return np.sort(arr)[-n]

In [64]:
arr = np.array([12, 34, 40, 7, 1, 0])
n = 3
print(nth_largest(arr, n))

12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [1]:
import numpy as np

a = np.array([1,2,3])
first = np.repeat(a, 3)
print(first)

second = np.tile(a, 3)
print(second)

c = np.concatenate((first,second))
print(c)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [67]:
result = np.resize(a, len(a)*3)
print(result)

[1 2 3 1 2 3 1 2 3]


In [5]:
c = np.tile(a, (3, 2))
print(c)


[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]
