<a href="https://colab.research.google.com/github/pranabsarma18/Python-Codes/blob/main/Numpy/Numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [201]:
import numpy as np
import matplotlib.pyplot as plt

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr = 
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [202]:
# code here
# i. np.sort

arr = np.array([[92, 90, 74],
               [ 6, 63, 93],
               [15, 93, 96],
               [70, 60, 48]])
arr

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [203]:
np.sort(arr)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [204]:
# ii. based on 2nd column
arr = np.array([[92, 90, 74],
               [ 6, 63, 93],
               [15, 93, 96],
               [70, 60, 48]])
arr

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [205]:
sorted_arr = arr[np.argsort(arr[:, 1])]
sorted_arr

array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [206]:
# iii. based on row max- ascending
# [[15 93 96]
#  [ 6 63 93]
#  [92 90 74]
#  [70 60 48]]

arr = np.array([[92, 90, 74],
               [ 6, 63, 93],
               [15, 93, 96],
               [70, 60, 48]])
arr

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [207]:
a = np.array([7, 4, 5, 1])
np.argsort(a)[::-1]

array([0, 2, 1, 3])

In [208]:
sorted_indices = np.argsort(np.amax(arr, axis=1))[::-1]
sorted_arr = arr[sorted_indices]
print(sorted_arr)

[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]


In [209]:
# iv. based on elements value
# [[ 6 15 48]
#  [60 63 70]
#  [74 90 92]
#  [93 93 96]]

In [210]:
arr = np.array([[92, 90, 74],
               [ 6, 63, 93],
               [15, 93, 96],
               [70, 60, 48]])
print(arr,'\n')
shape = np.shape(arr)
print(shape)

[[92 90 74]
 [ 6 63 93]
 [15 93 96]
 [70 60 48]] 

(4, 3)


In [211]:
np.sort?

In [212]:
sorted_arr = np.sort(arr, axis=None)
sorted_arr.reshape(shape)

array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [213]:
# code here
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
marks

array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

In [214]:
# i. Add marks every student of an extra subject in the same array.
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1, 1)
marks = np.append(marks, extra_subject, axis=1)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [215]:
# ii. Add two new students marks in respective 5 subjects.(one subject added in above task)

# Two extra students record-
# rec1 = [77, 83, 98, 95, 89]
# rec2 = [92, 71, 52, 61, 53]
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1, -1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1, -1)
marks = np.concatenate((marks, rec1, rec2), axis=0)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [216]:
# iii. Add extra column with sum of all subjects(5-subjects) marks
sum_all_subjects = np.sum(marks, axis=1).reshape(-1, 1)
marks = np.concatenate((marks, sum_all_subjects), axis=1)
marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [217]:
# iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.
sorted_student_index = np.argsort(marks[:,-1])[::-1]
sorted_students = marks[sorted_student_index]
sorted_students[:2,:]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [218]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [219]:
# Row Wise
np.unique(arr, axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [220]:
# Col Wise
np.unique(arr, axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [221]:
# code here
import numpy as np
a = np.array([[5, 3, 8], [1, 9, 2], [7, 4, 6]])
print(a)
print()
flipped_a = np.flip(a)
print(flipped_a)

[[5 3 8]
 [1 9 2]
 [7 4 6]]

[[6 4 7]
 [2 9 1]
 [8 3 5]]


In [222]:
np.flip?

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6
```

In [223]:
# code here
arr = np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]])

x = 6
arr1 = np.where(arr>6)[0]
np.unique(arr1)

array([1, 3])

In [224]:
np.argwhere?

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [225]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [226]:
# code here
flat_arr = np.concatenate((arr1, arr2, arr3),axis = 0)
print(flat_arr)

[0 1 2 3 4 5 6 7 8 9]


In [227]:
flat_arr1 = np.hstack((arr1, arr2, arr3))
flat_arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [262]:
# code here
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr.shape

(1, 200)

In [253]:
sum((arr[0] == np.amax(arr[0])) | (arr[0] == np.amin(arr[0])))

2

In [254]:
min_index = np.argmin(arr)
max_index = np.argmax(arr)
arr = np.delete(arr, [min_index, max_index])
arr.shape

(198,)

In [265]:
#My alternate
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr.shape

(1, 200)

In [266]:
np.where((arr[0]==998) | (arr[0]==103))

(array([ 66, 102]),)

In [267]:
arr = np.delete(arr[0], np.where((arr[0]==998) | (arr[0]==103))[0])

In [268]:
arr.shape

(198,)

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [285]:
# code here
arr = np.random.randint(100, 700, 200)
arr

array([553, 258, 664, 398, 203, 491, 103, 401, 213, 130, 284, 236, 681,
       284, 258, 138, 437, 303, 226, 407, 498, 446, 604, 187, 175, 332,
       627, 466, 228, 546, 140, 128, 385, 259, 672, 344, 503, 608, 123,
       438, 582, 678, 338, 292, 185, 458, 198, 421, 584, 361, 334, 467,
       435, 330, 381, 329, 618, 336, 186, 109, 288, 636, 381, 644, 573,
       169, 402, 465, 693, 571, 460, 465, 608, 684, 546, 553, 698, 453,
       643, 396, 626, 112, 198, 655, 401, 385, 175, 425, 597, 469, 580,
       400, 406, 355, 259, 502, 572, 471, 103, 604, 481, 478, 645, 125,
       390, 597, 493, 158, 403, 436, 380, 428, 286, 649, 455, 421, 568,
       344, 573, 163, 547, 531, 403, 534, 172, 377, 413, 576, 642, 305,
       377, 484, 682, 490, 246, 304, 321, 498, 240, 582, 276, 452, 629,
       512, 170, 482, 371, 286, 555, 439, 690, 167, 675, 259, 169, 431,
       632, 671, 492, 246, 310, 287, 372, 518, 499, 154, 348, 542, 246,
       428, 575, 274, 201, 460, 544, 661, 424, 304, 183, 259, 18

In [286]:
arr_cliped = np.clip(arr, a_min=100, a_max=200)
arr_cliped

array([200, 200, 200, 200, 200, 200, 103, 200, 200, 130, 200, 200, 200,
       200, 200, 138, 200, 200, 200, 200, 200, 200, 200, 187, 175, 200,
       200, 200, 200, 200, 140, 128, 200, 200, 200, 200, 200, 200, 123,
       200, 200, 200, 200, 200, 185, 200, 198, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 186, 109, 200, 200, 200, 200, 200,
       169, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 112, 198, 200, 200, 200, 175, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 103, 200, 200, 200, 200, 125,
       200, 200, 200, 158, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 163, 200, 200, 200, 200, 172, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 170, 200, 200, 200, 200, 200, 200, 167, 200, 200, 169, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 154, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 183, 200, 18

In [287]:
sorted_arr = np.sort(arr_cliped)
sorted_arr

array([103, 103, 109, 112, 123, 125, 128, 130, 138, 140, 154, 158, 163,
       167, 169, 169, 169, 170, 172, 175, 175, 183, 185, 186, 187, 189,
       198, 198, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 20

In [288]:
cum_sum = np.cumsum(sorted_arr)
cum_sum

array([  103,   206,   315,   427,   550,   675,   803,   933,  1071,
        1211,  1365,  1523,  1686,  1853,  2022,  2191,  2360,  2530,
        2702,  2877,  3052,  3235,  3420,  3606,  3793,  3982,  4180,
        4378,  4578,  4778,  4978,  5178,  5378,  5578,  5778,  5978,
        6178,  6378,  6578,  6778,  6978,  7178,  7378,  7578,  7778,
        7978,  8178,  8378,  8578,  8778,  8978,  9178,  9378,  9578,
        9778,  9978, 10178, 10378, 10578, 10778, 10978, 11178, 11378,
       11578, 11778, 11978, 12178, 12378, 12578, 12778, 12978, 13178,
       13378, 13578, 13778, 13978, 14178, 14378, 14578, 14778, 14978,
       15178, 15378, 15578, 15778, 15978, 16178, 16378, 16578, 16778,
       16978, 17178, 17378, 17578, 17778, 17978, 18178, 18378, 18578,
       18778, 18978, 19178, 19378, 19578, 19778, 19978, 20178, 20378,
       20578, 20778, 20978, 21178, 21378, 21578, 21778, 21978, 22178,
       22378, 22578, 22778, 22978, 23178, 23378, 23578, 23778, 23978,
       24178, 24378,

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [289]:
# code here
arr = np.linspace(0, 1, 50)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [290]:
arr = np.round(arr, 3)
arr

array([0.   , 0.02 , 0.041, 0.061, 0.082, 0.102, 0.122, 0.143, 0.163,
       0.184, 0.204, 0.224, 0.245, 0.265, 0.286, 0.306, 0.327, 0.347,
       0.367, 0.388, 0.408, 0.429, 0.449, 0.469, 0.49 , 0.51 , 0.531,
       0.551, 0.571, 0.592, 0.612, 0.633, 0.653, 0.673, 0.694, 0.714,
       0.735, 0.755, 0.776, 0.796, 0.816, 0.837, 0.857, 0.878, 0.898,
       0.918, 0.939, 0.959, 0.98 , 1.   ])

In [291]:
min_arr = np.amin(arr)
np.percentile(arr, 0) == min_arr

True

In [292]:
max_arr = np.amax(arr)
np.percentile(arr, 100) == max_arr

True

In [294]:
percentile_50 = np.percentile(arr, 50)
print(percentile_50)
percentile_51 = np.percentile(arr, 51)
print(percentile_51)
print(percentile_51 - percentile_50)

0.5
0.5098
0.009800000000000031
